# Generated by Django 5.0.1 on 2024-02-21 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Side', '0002_alter_category_soft_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50)),
                ('hotel_overview', models.TextField()),
                ('hotel_image', models.ImageField(blank=True, default='', null=True, upload_to='hotel_images/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Side.packages')),
            ],
        ),
    ]
