# Generated by Django 5.0.1 on 2024-02-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Side', '0003_hotels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='package',
        ),
        migrations.AddField(
            model_name='hotels',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='place',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
