# Generated by Django 5.0.1 on 2024-02-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Side', '0004_remove_hotels_package_hotels_is_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inclusions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='packages',
            name='exclusions',
            field=models.ManyToManyField(blank=True, to='Admin_Side.exclusions'),
        ),
        migrations.AddField(
            model_name='packages',
            name='inclusions',
            field=models.ManyToManyField(blank=True, to='Admin_Side.inclusions'),
        ),
    ]
