# Generated by Django 5.0.1 on 2024-02-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Side', '0005_exclusions_inclusions_packages_exclusions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='hotels',
            field=models.ManyToManyField(blank=True, to='Admin_Side.hotels'),
        ),
    ]
