# Generated by Django 5.0.1 on 2024-02-28 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Side', '0006_packages_hotels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinarary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('activities', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Side.packages')),
            ],
        ),
    ]
