# Generated by Django 5.0.1 on 2024-03-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Side', '0010_booking_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total',
        ),
    ]
