# Generated by Django 5.0.1 on 2024-03-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Side', '0015_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='package_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
