# Generated by Django 5.0.1 on 2024-03-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Side', '0018_booking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Stripe', 'Stripe'), ('Wallet', 'Wallet'), ('Not-paid', 'Not-paid')], default='Not paid', max_length=20),
        ),
    ]
