# Generated by Django 5.0.1 on 2024-03-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Side', '0025_alter_wallettransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='wallet_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
